# Generated by Django 4.1.13 on 2024-01-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="resume",
        ),
    ]
