# Generated by Django 4.1.13 on 2024-01-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0004_job_application_deadline_alter_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="job_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
