# Generated by Django 4.2.5 on 2024-01-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0006_jobapplicants_remove_job_applicants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Applicant",
        ),
    ]
